name: Test All Data Download (download_all_aihw_data)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run weekly to test against live API
    - cron: '0 6 * * 1'

jobs:
  test-bulk-download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Test bulk download functions
        run: |
          Rscript -e "
          library(testthat)
          library(readaihw)

          # Test with timeout to avoid long CI runs
          result <- try({
            R.utils::withTimeout({
              data <- download_all_aihw_data('test_data.rds', force = TRUE)
              testthat::expect_true(file.exists('test_data.rds'))
              testthat::expect_true('flat_data' %in% names(data))
              message('Bulk download test passed')
            }, timeout = 300) # 5 minute timeout
          }, silent = FALSE)

          if (inherits(result, 'try-error')) {
            message('Bulk download test skipped due to timeout or network issues')
          }
          "
